name: Publish Package to npmjs

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package*.json'

jobs:
  avoid_reduncy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_DEPLOY_TOKEN }}
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependecies
        run: npm ci
      - name: Run workspaces unit tests
        run: npm test -- workspaces.test.ts
        env:
          X_AUTH_TOKEN: ${{ secrets.DEEPINT_AUTH_TOKEN }}
          X_DEEPINT_ORGANIZATION: ${{ secrets.DEEPINT_TEST_ORGANIZATION }}
          CLIENT_ID: ${{ secrets.DEEPINT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.DEEPINT_CLIENT_SECRET }}
          BEARER_TOKEN: ${{ secrets.DEEPINT_BEARER_TOKEN }}
      - name: Run sources unit tests
        run: npm test -- sources.test.ts
        env:
          X_AUTH_TOKEN: ${{ secrets.DEEPINT_AUTH_TOKEN }}
          X_DEEPINT_ORGANIZATION: ${{ secrets.DEEPINT_TEST_ORGANIZATION }}
          CLIENT_ID: ${{ secrets.DEEPINT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.DEEPINT_CLIENT_SECRET }}
          BEARER_TOKEN: ${{ secrets.DEEPINT_BEARER_TOKEN }}
      - name: Run dashboards unit tests
        run: npm test -- dashboards.test.ts
        env:
          X_AUTH_TOKEN: ${{ secrets.DEEPINT_AUTH_TOKEN }}
          X_DEEPINT_ORGANIZATION: ${{ secrets.DEEPINT_TEST_ORGANIZATION }}
          CLIENT_ID: ${{ secrets.DEEPINT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.DEEPINT_CLIENT_SECRET }}
          BEARER_TOKEN: ${{ secrets.DEEPINT_BEARER_TOKEN }}
      - name: Run visualizations unit tests
        run: npm test -- visualizations.test.ts
        env:
          X_AUTH_TOKEN: ${{ secrets.DEEPINT_AUTH_TOKEN }}
          X_DEEPINT_ORGANIZATION: ${{ secrets.DEEPINT_TEST_ORGANIZATION }}
          CLIENT_ID: ${{ secrets.DEEPINT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.DEEPINT_CLIENT_SECRET }}
          BEARER_TOKEN: ${{ secrets.DEEPINT_BEARER_TOKEN }}
      - name: Run account unit tests
        run: npm test -- account.test.ts
        env:
          X_AUTH_TOKEN: ${{ secrets.DEEPINT_AUTH_TOKEN }}
          X_DEEPINT_ORGANIZATION: ${{ secrets.DEEPINT_TEST_ORGANIZATION }}
          CLIENT_ID: ${{ secrets.DEEPINT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.DEEPINT_CLIENT_SECRET }}
          BEARER_TOKEN: ${{ secrets.DEEPINT_BEARER_TOKEN }}
      - name: Run alerts unit tests
        run: npm test -- alerts.test.ts
        env:
          X_AUTH_TOKEN: ${{ secrets.DEEPINT_AUTH_TOKEN }}
          X_DEEPINT_ORGANIZATION: ${{ secrets.DEEPINT_TEST_ORGANIZATION }}
          CLIENT_ID: ${{ secrets.DEEPINT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.DEEPINT_CLIENT_SECRET }}
          BEARER_TOKEN: ${{ secrets.DEEPINT_BEARER_TOKEN }}
      - name: Run authentification unit tests
        run: npm test -- authentification.test.ts
        env:
          X_AUTH_TOKEN: ${{ secrets.DEEPINT_AUTH_TOKEN }}
          X_DEEPINT_ORGANIZATION: ${{ secrets.DEEPINT_TEST_ORGANIZATION }}
          CLIENT_ID: ${{ secrets.DEEPINT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.DEEPINT_CLIENT_SECRET }}
          BEARER_TOKEN: ${{ secrets.DEEPINT_BEARER_TOKEN }}
      - name: Run emails unit tests
        run: npm test -- emails.test.ts
        env:
          X_AUTH_TOKEN: ${{ secrets.DEEPINT_AUTH_TOKEN }}
          X_DEEPINT_ORGANIZATION: ${{ secrets.DEEPINT_TEST_ORGANIZATION }}
          CLIENT_ID: ${{ secrets.DEEPINT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.DEEPINT_CLIENT_SECRET }}
          BEARER_TOKEN: ${{ secrets.DEEPINT_BEARER_TOKEN }}
      - name: Run tasks unit tests
        run: npm test -- tasks.test.ts
        env:
          X_AUTH_TOKEN: ${{ secrets.DEEPINT_AUTH_TOKEN }}
          X_DEEPINT_ORGANIZATION: ${{ secrets.DEEPINT_TEST_ORGANIZATION }}
          CLIENT_ID: ${{ secrets.DEEPINT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.DEEPINT_CLIENT_SECRET }}
          BEARER_TOKEN: ${{ secrets.DEEPINT_BEARER_TOKEN }}

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_DEPLOY_TOKEN }}
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Set git email
        run: git config user.email ${{ secrets.GIT_EMAIL }}
      - name: Set github username
        run: git config user.name ${{ secrets.GIT_NAME }}
      - name: Run npm version patch to increase version
        run: npm version patch
      - name: Update version on repository
        run: git push
      - name: Install node dependecies
        run: npm ci
      - name: Build dist package to be deployed
        run: npm run build
      - name: Add types to dist package
        run: cp src/types.d.ts dist/
      - name: Publish package to npm registry
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
